'use client';

import React, { useState, useEffect } from 'react';
import {
  Package, MapPin, Clock, CheckCircle2,
  ArrowRight, Download, Search, LayoutDashboard,
  Box, TrendingUp, Calendar, User, Mail, Phone,
  FileText, ShieldCheck, Globe, Loader2, AlertCircle,
  LogOut, History as LucideHistory, DollarSign, Navigation, Shield
} from 'lucide-react';
import { shipmentService, authService } from '@/services/api';
import { useAuth } from '@/store/AuthContext';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import NotificationBell from '@/components/NotificationBell';
import { motion, AnimatePresence } from 'framer-motion';

export default function UserDashboard() {
  const { user, logout } = useAuth();
  const router = useRouter();
  const [shipments, setShipments] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedShipment, setSelectedShipment] = useState<any>(null);
  const [stats, setStats] = useState({
    active: 0,
    delivered: 0,
    total: 0
  });

  useEffect(() => {
    if (!user) {
      router.push('/login');
      return;
    }
    fetchShipments();
  }, [user, router]);

  const fetchShipments = async () => {
    try {
      setLoading(true);
      const data = (await shipmentService.getMyShipments()) as any[];
      setShipments(data);

      const active = data.filter((s: any) => s.shipmentStatus !== 'Delivered' && s.shipmentStatus !== 'Cancelled').length;
      const delivered = data.filter((s: any) => s.shipmentStatus === 'Delivered').length;

      setStats({
        active,
        delivered,
        total: data.length
      });

      if (data.length > 0) {
        setSelectedShipment(data[0]);
      }
    } catch (error) {
      console.error('Failed to fetch shipments', error);
    } finally {
      setLoading(false);
    }
  };

  const handleLogout = () => {
    logout();
    router.push('/login');
  };

  const getWorkflowProgress = (status: string) => {
    const workflow = ['Pending', 'Transit', 'Sorting Hub', 'Warehouse', 'Pending Pickup', 'Delivered'];
    const index = workflow.indexOf(status);
    return ((index + 1) / workflow.length) * 100;
  };

  const downloadReceipt = (shipment: any) => {
    const content = `
SWIFTLOGIX SHIPMENT RECEIPT
--------------------------
Tracking Number: ${shipment.trackingNumber}
Status: ${shipment.shipmentStatus}
Date: ${new Date().toLocaleDateString()}

SENDER DETAILS:
Name: ${shipment.senderName}
Address: ${shipment.senderAddress}

RECEIVER DETAILS:
Name: ${shipment.receiverName}
Address: ${shipment.receiverAddress}

PACKAGE INFO:
Weight: ${shipment.packageWeight || 'N/A'}
Type: ${shipment.packageType || 'N/A'}

Generated by SwiftLogix System
    `;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Receipt_${shipment.trackingNumber}.txt`;
    link.click();
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-[#0f172a] flex items-center justify-center">
        <Loader2 className="w-12 h-12 text-blue-500 animate-spin" />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#070b14] text-white flex">
      {/* Sidebar */}
      <aside className="w-80 glass-panel p-8 hidden lg:flex flex-col gap-10 border-r border-white/5">
        <div className="flex items-center gap-3">
          <div className="bg-blue-600 p-2.5 rounded-2xl shadow-[0_0_20px_rgba(37,99,235,0.4)]">
            <Globe className="w-6 h-6 text-white" />
          </div>
          <span className="text-2xl font-black tracking-tighter uppercase italic">SwiftLogix</span>
        </div>

        <div className="space-y-3">
          <p className="text-[10px] font-black text-slate-500 uppercase tracking-[0.3em] px-4 mb-6">Network Nodes</p>
          <button className="flex items-center gap-4 w-full px-5 py-4 bg-blue-600 rounded-2xl text-white shadow-[0_10px_30px_rgba(37,99,235,0.3)] font-black transition-all">
            <LayoutDashboard className="w-5 h-5" /> My Workflow
          </button>
          <button
            onClick={() => router.push('/track')}
            className="flex items-center gap-4 w-full px-5 py-4 text-slate-500 hover:text-blue-400 hover:bg-blue-500/5 rounded-2xl font-bold transition-all border border-transparent hover:border-blue-500/20"
          >
            <Search className="w-5 h-5" /> Global Trace
          </button>
        </div>

        <div className="mt-auto logistics-card p-6 !rounded-[2.5rem]">
          <div className="flex items-center gap-4 mb-6">
            <div className="bg-blue-500/10 p-3 rounded-2xl border border-blue-500/20">
              <User className="w-5 h-5 text-[#FFB800]" />
            </div>
            <div className="overflow-hidden">
              <p className="font-black text-sm text-white truncate">{user?.name}</p>
              <p className="text-[10px] text-slate-500 font-bold uppercase tracking-widest truncate">{user?.email}</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <div className="flex-1 drop-shadow-lg">
              <NotificationBell />
            </div>
            <button
              onClick={handleLogout}
              className="bg-red-500/10 hover:bg-red-500 text-red-500 hover:text-white p-3 rounded-2xl transition-all border border-red-500/20"
              title="Logout"
            >
              <LogOut className="w-5 h-5" />
            </button>
          </div>
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 p-8 md:p-14 overflow-y-auto max-h-screen custom-scrollbar bg-dot-pattern">
        <header className="flex flex-col xl:flex-row justify-between items-start xl:items-center gap-8 mb-16">
          <div>
            <div className="flex items-center gap-3 mb-4">
              <span className="w-2 h-2 bg-emerald-500 rounded-full animate-pulse shadow-[0_0_10px_rgba(16,185,129,0.5)]" />
              <span className="text-[10px] font-black text-slate-500 uppercase tracking-[0.3em]">Session Secured & Active</span>
            </div>
            <h1 className="text-5xl md:text-6xl font-black tracking-tighter mb-4 gradient-text">Command Center</h1>
            <p className="text-slate-400 text-lg font-medium">Hello, <span className="text-blue-500 font-black">{user?.name.split(' ')[0]}</span>. You have <span className="text-[#FFB800] font-black">{stats.active}</span> shipments in transit.</p>
          </div>

          <div className="flex gap-6 w-full md:w-auto">
            <div className="logistics-card px-10 py-6 flex-1 md:flex-none flex items-center gap-6 group hover:border-blue-500/30 transition-all">
              <div className="p-4 bg-blue-600 rounded-3xl shadow-[0_10px_20px_rgba(37,99,235,0.3)] group-hover:scale-110 transition-transform">
                <Package className="w-7 h-7 text-white" />
              </div>
              <div>
                <p className="text-4xl font-black text-white leading-none">{stats.total}</p>
                <p className="text-[10px] text-slate-500 font-black uppercase tracking-[0.2em] mt-1">Total Payload</p>
              </div>
            </div>
            <div className="logistics-card px-10 py-6 flex-1 md:flex-none flex items-center gap-6 group hover:border-emerald-500/30 transition-all">
              <div className="p-4 bg-emerald-600 rounded-3xl shadow-[0_10px_20px_rgba(16,185,129,0.3)] group-hover:scale-110 transition-transform">
                <CheckCircle2 className="w-7 h-7 text-white" />
              </div>
              <div>
                <p className="text-4xl font-black text-white leading-none">{stats.delivered}</p>
                <p className="text-[10px] text-slate-500 font-black uppercase tracking-[0.2em] mt-1">Completed</p>
              </div>
            </div>
          </div>
        </header>

        <div className="grid grid-cols-1 xl:grid-cols-3 gap-8">
          {/* List Section */}
          <div className="xl:col-span-1 space-y-6">
            <h3 className="text-xl font-black mb-6 flex items-center gap-3">
              <LucideHistory className="w-5 h-5 text-blue-500" /> Active Registry
            </h3>
            <div className="space-y-4 max-h-[700px] overflow-y-auto pr-3 custom-scrollbar">
              {shipments.length === 0 ? (
                <div className="logistics-card p-12 text-center opacity-50">
                  <AlertCircle className="w-12 h-12 text-slate-700 mx-auto mb-4" />
                  <p className="text-slate-500 font-bold uppercase tracking-widest text-xs">No active nodes detected</p>
                </div>
              ) : (
                shipments.map((s) => (
                  <motion.div
                    layout
                    key={s.id}
                    onClick={() => setSelectedShipment(s)}
                    className={`logistics-card p-6 cursor-pointer transition-all duration-300 border-2 ${selectedShipment?.id === s.id
                        ? 'border-[#FFB800] bg-blue-500/5 shadow-[0_10px_30px_rgba(255,184,0,0.15)] scale-[1.02]'
                        : 'border-transparent hover:border-white/10'
                      }`}
                  >
                    <div className="flex justify-between items-start mb-4">
                      <div className="p-3 bg-slate-900 rounded-2xl">
                        <Package className={`w-5 h-5 ${selectedShipment?.id === s.id ? 'text-[#FFB800]' : 'text-blue-500'}`} />
                      </div>
                      <span className={`text-[10px] font-black px-3 py-1 rounded-full uppercase tracking-widest ${s.shipmentStatus === 'Delivered' ? 'bg-emerald-500/10 text-emerald-500' :
                          s.shipmentStatus === 'In Transit' ? 'bg-blue-500/10 text-blue-500' :
                            'bg-[#FFB800]/10 text-[#FFB800]'
                        }`}>
                        {s.shipmentStatus}
                      </span>
                    </div>
                    <p className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-1">Waybill Number</p>
                    <p className="text-xl font-black text-white tracking-tight mb-4">{s.trackingNumber}</p>
                    <div className="flex items-center gap-2 text-slate-400">
                      <MapPin className="w-3.5 h-3.5 text-blue-500" />
                      <p className="text-xs font-bold truncate">{s.senderAddress}</p>
                    </div>
                  </motion.div>
                ))
              )}
            </div>
          </div>

          {/* Details Section */}
          <AnimatePresence mode="wait">
            {selectedShipment && (
              <motion.div
                key={selectedShipment.id}
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="xl:col-span-2 space-y-8"
              >
                {/* Master Details Card */}
                <div className="glass rounded-[40px] p-8 md:p-10 border border-slate-800/50 relative overflow-hidden">
                  <div className="absolute top-0 right-0 p-8">
                    <Package className="w-32 h-32 text-blue-500 opacity-5 -scale-x-100 rotate-12" />
                  </div>

                  <div className="flex flex-col md:flex-row justify-between gap-6 mb-10 pb-8 border-b border-slate-800/50">
                    <div>
                      <p className="text-xs font-bold text-slate-500 uppercase tracking-[0.2em] mb-2">Tracking ID</p>
                      <h2 className="text-3xl md:text-4xl font-black text-blue-400">{selectedShipment.trackingNumber}</h2>
                    </div>
                    <div className="flex gap-3">
                      <button
                        onClick={() => downloadReceipt(selectedShipment)}
                        className="px-6 py-3 bg-slate-800 hover:bg-slate-700 rounded-2xl flex items-center gap-2 font-bold transition-all text-sm"
                      >
                        <FileText className="w-4 h-4 text-blue-500" /> Receipt
                      </button>
                      <button className="px-6 py-3 bg-blue-600 hover:bg-blue-500 rounded-2xl flex items-center gap-2 font-bold shadow-lg shadow-blue-900/30 transition-all text-sm">
                        <Download className="w-4 h-4" /> Export Data
                      </button>
                    </div>
                  </div>

                  {/* Modern Timeline */}
                  <div className="mb-12">
                    <div className="flex justify-between items-center mb-6">
                      <h4 className="text-lg font-bold flex items-center gap-2">
                        <TrendingUp className="w-5 h-5 text-blue-500" /> Real-time Progress
                      </h4>
                      <span className="text-xs font-bold bg-blue-500/10 text-blue-400 px-3 py-1 rounded-full uppercase tracking-widest border border-blue-500/20 animate-pulse">
                        Live
                      </span>
                    </div>

                    <div className="relative pt-12 pb-12">
                      <div className="absolute top-1/2 left-0 w-full h-1.5 bg-slate-800 rounded-full -translate-y-1/2" />
                      <motion.div
                        initial={{ width: 0 }}
                        animate={{ width: `${getWorkflowProgress(selectedShipment.shipmentStatus)}%` }}
                        transition={{ duration: 1.5, ease: "easeOut" }}
                        className="absolute top-1/2 left-0 h-1.5 bg-blue-500 rounded-full -translate-y-1/2 shadow-[0_0_20px_rgba(59,130,246,0.5)]"
                      />

                      <div className="flex justify-between relative z-10 px-2">
                        {['Transit', 'Sorting Hub', 'Warehouse', 'Pending Pickup', 'Delivered'].map((step, i) => {
                          const workflow = ['Transit', 'Sorting Hub', 'Warehouse', 'Pending Pickup', 'Delivered'];
                          const currentIndex = workflow.indexOf(selectedShipment.shipmentStatus);
                          const isActive = workflow.indexOf(step) <= currentIndex;
                          const isCurrent = step === selectedShipment.shipmentStatus;

                          return (
                            <div key={step} className="flex flex-col items-center gap-4">
                              <div className={`w-10 h-10 rounded-2xl flex items-center justify-center transition-all duration-500 ${isActive ? 'bg-blue-600 shadow-xl shadow-blue-900/40 text-white' : 'bg-slate-800 text-slate-600'
                                } ${isCurrent ? 'scale-125 border-4 border-slate-900' : 'scale-100'}`}>
                                {step === 'Delivered' ? <CheckCircle2 className="w-5 h-5" /> : (i + 1)}
                              </div>
                              <p className={`text-[10px] md:text-xs font-bold uppercase tracking-tighter w-16 text-center leading-tight ${isActive ? 'text-blue-400' : 'text-slate-600'}`}>{step}</p>
                            </div>
                          );
                        })}
                      </div>
                    </div>
                  </div>

                  {/* Sub Details */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                    <div className="space-y-6">
                      <div className="p-6 bg-slate-950/40 rounded-3xl border border-slate-800/50">
                        <h5 className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-4 flex items-center gap-2">
                          <MapPin className="w-3 h-3 text-blue-500" /> Origin & Destination
                        </h5>
                        <div className="space-y-4">
                          <div className="flex gap-4">
                            <div className="w-1.5 bg-blue-500 rounded-full" />
                            <div>
                              <p className="text-slate-400 text-xs font-medium">Sender Address</p>
                              <p className="font-bold text-sm">{selectedShipment.senderAddress}</p>
                            </div>
                          </div>
                          <div className="flex gap-4">
                            <div className="w-1.5 bg-emerald-500 rounded-full" />
                            <div>
                              <p className="text-slate-400 text-xs font-medium">Recipient Address</p>
                              <p className="font-bold text-sm">{selectedShipment.receiverAddress}</p>
                            </div>
                          </div>
                        </div>
                      </div>

                      <div className="p-6 bg-slate-950/40 rounded-3xl border border-slate-800/50 grid grid-cols-2 gap-4">
                        <div>
                          <p className="text-slate-500 text-[10px] uppercase font-bold tracking-widest mb-1">Weight</p>
                          <p className="font-bold flex items-center gap-2"><Box className="w-4 h-4 text-blue-500" /> {selectedShipment.packageWeight || '12.5 kg'}</p>
                        </div>
                        <div>
                          <p className="text-slate-500 text-[10px] uppercase font-bold tracking-widest mb-1">Package Type</p>
                          <p className="font-bold flex items-center gap-2"><ShieldCheck className="w-4 h-4 text-emerald-500" /> {selectedShipment.packageType || 'Secured Box'}</p>
                        </div>
                      </div>
                    </div>

                    {/* History Log */}
                    <div className="p-8 bg-slate-950/40 rounded-[32px] border border-slate-800/50 max-h-[400px] overflow-y-auto custom-scrollbar">
                      <h5 className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-6 flex items-center gap-2 sticky top-0 bg-[#0f172a]/80 backdrop-blur pb-2">
                        <LucideHistory className="w-3 h-3 text-blue-500" /> Movement Logs
                      </h5>
                      <div className="space-y-8 relative">
                        <div className="absolute left-3 top-2 bottom-2 w-0.5 bg-slate-800" />
                        {selectedShipment.history && [...selectedShipment.history].reverse().map((log: any, i: number) => (
                          <div key={i} className="flex gap-6 relative">
                            <div className={`w-6 h-6 rounded-full flex items-center justify-center z-10 shadow-lg ${i === 0 ? 'bg-blue-500' : 'bg-slate-800'}`}>
                              <div className={`w-2 h-2 rounded-full ${i === 0 ? 'bg-white' : 'bg-slate-600'}`} />
                            </div>
                            <div className="flex-1">
                              <div className="flex justify-between items-start mb-1">
                                <p className={`font-bold text-sm ${i === 0 ? 'text-blue-400' : 'text-slate-300'}`}>{log.status}</p>
                                <span className="text-[10px] text-slate-500 font-bold">{new Date(log.timestamp).toLocaleDateString()}</span>
                              </div>
                              <p className="text-xs text-slate-400 font-medium leading-relaxed">{log.description || `Shipment arrived at ${log.location}`}</p>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>

                  {/* Financial Visibility Section */}
                  {selectedShipment.showFinancials && (
                    <motion.div
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      className="mt-12 p-8 bg-[#FFB800]/5 rounded-[2.5rem] border border-[#FFB800]/20 relative overflow-hidden"
                    >
                      <div className="absolute top-0 right-0 p-8 opacity-[0.03] pointer-events-none">
                        <DollarSign className="w-48 h-48" />
                      </div>

                      <div className="flex items-center gap-4 mb-8">
                        <div className="w-12 h-12 bg-[#FFB800] rounded-2xl flex items-center justify-center shadow-lg shadow-[#FFB800]/30">
                          <DollarSign className="w-6 h-6 text-slate-900" />
                        </div>
                        <div>
                          <h4 className="text-xl font-black text-white italic uppercase tracking-tighter">Financial Transparency</h4>
                          <p className="text-[10px] font-black text-[#FFB800] uppercase tracking-widest">Official Fiscal node Log</p>
                        </div>
                      </div>

                      <div className="grid grid-cols-2 lg:grid-cols-4 gap-6">
                        {[
                          { label: 'Customs Node', value: selectedShipment.customsFees, icon: ShieldCheck },
                          { label: 'Insurance Node', value: selectedShipment.insuranceFees, icon: Shield },
                          { label: 'Delivery Ops', value: selectedShipment.deliveryCharges, icon: Navigation },
                          { label: 'Storage Node', value: selectedShipment.storageFees, icon: Box }
                        ].map((fee, idx) => (
                          <div key={idx} className="bg-slate-950/60 p-5 rounded-2xl border border-white/5 group hover:border-[#FFB800]/30 transition-all">
                            <div className="flex items-center gap-2 mb-3">
                              <div className="w-3.5 h-3.5 text-[#FFB800]">
                                {idx === 0 ? <ShieldCheck className="w-full h-full" /> :
                                  idx === 1 ? <Shield className="w-full h-full" /> :
                                    idx === 2 ? <Navigation className="w-full h-full" /> :
                                      <Box className="w-full h-full" />}
                              </div>
                              <span className="text-[9px] font-black text-slate-500 uppercase tracking-widest">{fee.label}</span>
                            </div>
                            <p className="text-2xl font-black text-white tracking-tighter">${Number(fee.value || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}</p>
                          </div>
                        ))}
                      </div>

                      <div className="mt-8 pt-8 border-t border-white/5 flex flex-col md:flex-row justify-between items-center gap-6">
                        <div className="flex items-center gap-3">
                          <div className="w-2 h-2 bg-emerald-500 rounded-full animate-pulse shadow-[0_0_10px_rgba(16,185,129,0.5)]" />
                          <p className="text-[10px] font-black text-slate-500 uppercase tracking-widest">Verified by SwiftLogix Global Finance</p>
                        </div>
                        <div className="flex items-center gap-4">
                          <p className="text-xs font-black text-slate-400 uppercase tracking-widest">Total Liability:</p>
                          <p className="text-3xl font-black text-[#FFB800] tracking-tighter">
                            ${(
                              Number(selectedShipment.customsFees || 0) +
                              Number(selectedShipment.insuranceFees || 0) +
                              Number(selectedShipment.deliveryCharges || 0) +
                              Number(selectedShipment.storageFees || 0)
                            ).toLocaleString(undefined, { minimumFractionDigits: 2 })}
                          </p>
                        </div>
                      </div>
                    </motion.div>
                  )}
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </main>

    </div>
  );
}
